
Vagrant.configure("2") do |config|

    config.vm.box = "bento/ubuntu-20.04-arm64"
    config.vm.network  "public_network", ip: "192.168.1.20"
    config.vm.provider  "vmware_desktop" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
      vb.vmx['displayname'] = 'Deploy 2'
      #vb.vmx.network "public_network", ip: "192.168.1.10"
    end
    #config.vm.boot_timeout = "1000"
    config.vm.provision "shell", path: "script.sh"
  
  end
  